//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bank_DAL
{
    using System;
    
    public partial class address
    {
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
    }
}
