//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bank_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public int loan_Id { get; set; }
        public string loantype { get; set; }
        public string amount { get; set; }
        public string duration { get; set; }
        public string rateofintrest { get; set; }
    }
}
